name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest # On utilise une machine virtuelle Linux fournie par GitHub

    steps:
      # 1. Récupérer le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Se connecter à Docker Hub (Indispensable pour pouvoir 'push')
      # On utilise les SECRETS configurés à l'étape 3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Configurer l'environnement de build Docker (Buildx)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Construire l'image et l'envoyer (Push)
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/github-action-project:latest